### ISSUE TITLE
No english flag

### ISSUE THREAD

**Issue by sprenger-hauke** [HizurosWoWAddOns/TooltipRealmInfo#1]
Hi,
for a friend and me it never shows the english flag on english speaking servers (Europe) like Ravencrest or Tarrens Mill.

Is this the intended behaviour? Is there a easy way to fix this?

Greetings

**Comment by hizuro** [comment]
I've created a character on Tarren Mill.  Currently i see no problems.
![ttri_test1](https://user-images.githubusercontent.com/1668117/172257929-b349c7bd-dd17-4be3-abd6-676de4b4f0ca.jpg)
Please check your config.
![ttri_test2](https://user-images.githubusercontent.com/1668117/172258027-13b6a725-06d7-4183-a4f9-5619a4ba49f2.jpg)

**Comment by sprenger-hauke** [comment]
Ah my bad, I am using your tool mostly for flags in chat. The problem with the missing flags is only in chat. Everything else works fine. Sorry for forgetting this important detail. @hizuro

**Comment by hizuro** [comment]
;-) 
Do you use the befault chat window or addon like WIM?

**Comment by sprenger-hauke** [comment]
> ;-) Do you use the befault chat window or addon like WIM?

I am using default chat window. My friend is using ElvUI (I don't know if that changes things around with chat).

**Comment by sprenger-hauke** [comment]
Here is a image where you can see it.
https://imgur.com/a/4NvfNuY

**Comment by hizuro** [comment]
Wirklich seltsam. Muss jetzt aus dem Haus. Schau es mir später nochmal an. ;-)

**Comment by sprenger-hauke** [comment]
> Wirklich seltsam. Muss jetzt aus dem Haus. Schau es mir später nochmal an. ;-)

Alles klar 😆

**Comment by hizuro** [comment]
Da wurd es gestern später als erwartet. Wenn du möchtest, könntest du mir auch dabei Helfen. Hab eine Version mit debug Ausgaben gepackt. ~TooltipRealmInfo-1.2.7-release-7-g062e29e.zip~

Werden aber nicht im Chat ausgegeben. Dafür müsstest du die Console aktivieren. Blizzard App > Einstellungen > Spieleinstellungen > Haken bei "Zusätzliche Befehlszeilenargumente" > in die erscheinende Zeile `-console` einfügen.

*Huch, weiß ja gar nicht auf welchem OS du spielst. Unter [Console](https://wowpedia.fandom.com/wiki/Console) findest du auch die anderen Optionen die Console zu verfügbar zu machen.*

Benutzt du zum spielen die Englische Tastaturbelegung, kannst du sie mit dem \`-Aktzentzeichen öffnen. Andernfalls empfehle ich `/run SetConsoleKey("F9")` mit einer Taste deiner Wahl auszuführen. Dann kannst du die Console mit dieser öffnen.

Die Console hat von Haus aus eine Mark-Copy-Funktion. Die Debug Ausgaben sollten ins Auge fallen. ;-)

**Comment by sprenger-hauke** [comment]
> Da wurd es gestern später als erwartet. Wenn du möchtest, könntest du mir auch dabei Helfen. Hab eine Version mit debug Ausgaben gepackt. [TooltipRealmInfo-1.2.7-release-7-g062e29e.zip](https://misc.hizuro.de/files/TooltipRealmInfo-1.2.7-release-7-g062e29e.zip)
> 
> Werden aber nicht im Chat ausgegeben. Dafür müsstest du die Console aktivieren. Blizzard App > Einstellungen > Spieleinstellungen > Haken bei "Zusätzliche Befehlszeilenargumente" > in die erscheinende Zeile `-console` einfügen.
> 
> _Huch, weiß ja gar nicht auf welchem OS du spielst. Unter [Console](https://wowpedia.fandom.com/wiki/Console) findest du auch die anderen Optionen die Console zu verfügbar zu machen._
> 
> Benutzt du zum spielen die Englische Tastaturbelegung, kannst du sie mit dem `-Aktzentzeichen öffnen. Andernfalls empfehle ich `/run SetConsoleKey("F9")` mit einer Taste deiner Wahl auszuführen. Dann kannst du die Console mit dieser öffnen.
> 
> Die Console hat von Haus aus eine Mark-Copy-Funktion. Die Debug Ausgaben sollten ins Auge fallen. ;-)

Bei mir ist ist heute auch später geworden. Falls du die Daten noch benötigst, würde ich das morgen Abend mal machen.

**Comment by hizuro** [comment]
Wäre schon schön. Hab keine Chars auf englischen Realms, die raiden könnten. Der normale Chat geht. Wundert mich aber immernoch. Es ist die gleiche Filterfunktion, die sowohl den Raid als auch alle anderen Channel zu sehen bekommt. 

Nachtrag: Die gesonderte Datei musst du nun doch nicht runterladen. Lade gleich ein offizielles Update für eine andere Fehlermeldung hoch.

**Comment by sprenger-hauke** [comment]
> Wäre schon schön. Hab keine Chars auf englischen Realms, die raiden könnten. Der normale Chat geht. Wundert mich aber immernoch. Es ist die gleiche Filterfunktion, die sowohl den Raid als auch alle anderen Channel zu sehen bekommt.
> 
> Nachtrag: Die gesonderte Datei musst du nun doch nicht runterladen. Lade gleich ein offizielles Update für eine andere Fehlermeldung hoch.

Der Download führt eh ins Leere :D

**Comment by hizuro** [comment]
Japp. Hatte ihn gelöscht, da die Debugausgaben auch in der neuen Version 1.2.8 enthalten sind. ;-)

**Comment by sprenger-hauke** [comment]
> |cff99999919:18:07|r |cff82c5ffTooltipRealmInfo|r: |cff00ff00<CCF>|r |cffff6060nil|r |cff44ffff14|r |cffffff00Player-3674-08D03F53|r |cffff8800table|r |cffff44ff{"1":"625","2":"Twisting Nether","3":"TwistingNether","4":"PvE","5":"enGB","7":"EU","8":"UTC+1","9":"table: 0000025E5A387CB0","12":"|TInterface\AddOns\TooltipRealmInfo\media\enGB:0:2|t","13":"Interface\AddOns\TooltipRealmInfo\media\enGB"}|r
|cff99999919:18:07|r |cff82c5ffTooltipRealmInfo|r: |cff00ff00<CCF>|r |cffff6060nil|r |cff44ffff14|r |cffffff00Player-3674-08D03F53|r |cffff8800table|r |cffff44ff{"1":"625","2":"Twisting Nether","3":"TwistingNether","4":"PvE","5":"enGB","7":"EU","8":"UTC+1","9":"table: 0000025E5A38AA50","12":"|TInterface\AddOns\TooltipRealmInfo\media\enGB:0:2|t","13":"Interface\AddOns\TooltipRealmInfo\media\enGB"}|r
|cff99999919:18:18|r |cff82c5ffTooltipRealmInfo|r: |cff00ff00<CCF>|r |cffff6060nil|r |cff44ffff14|r |cffffff00Player-3674-08D03F53|r |cffff8800table|r |cffff44ff{"1":"625","2":"Twisting Nether","3":"TwistingNether","4":"PvE","5":"enGB","7":"EU","8":"UTC+1","9":"table: 0000025EBBBD20C0","12":"|TInterface\AddOns\TooltipRealmInfo\media\enGB:0:2|t","13":"Interface\AddOns\TooltipRealmInfo\media\enGB"}|r
|cff99999919:18:21|r |cff82c5ffTooltipRealmInfo|r: |cff00ff00<CCF>|r |cffff6060nil|r |cff44ffff14|r |cffffff00Player-3674-08D03F53|r |cffff8800table|r |cffff44ff{"1":"625","2":"Twisting Nether","3":"TwistingNether","4":"PvE","5":"enGB","7":"EU","8":"UTC+1","9":"table: 0000025E7E1B7EA0","12":"|TInterface\AddOns\TooltipRealmInfo\media\enGB:0:2|t","13":"Interface\AddOns\TooltipRealmInfo\media\enGB"}|r
|cff99999919:18:21|r |cff82c5ffTooltipRealmInfo|r: |cff00ff00<CCF>|r |cffff6060nil|r |cff44ffff14|r |cffffff00Player-3674-08D03F53|r |cffff8800table|r |cffff44ff{"1":"625","2":"Twisting Nether","3":"TwistingNether","4":"PvE","5":"enGB","7":"EU","8":"UTC+1","9":"table: 0000025E7E1B8170","12":"|TInterface\AddOns\TooltipRealmInfo\media\enGB:0:2|t","13":"Interface\AddOns\TooltipRealmInfo\media\enGB"}|r
|cff99999919:18:29|r |cff82c5ffTooltipRealmInfo|r: |cff00ff00<CCF>|r |cffff6060nil|r |cff44ffff14|r |cffffff00Player-3674-08D03F53|r |cffff8800table|r |cffff44ff{"1":"625","2":"Twisting Nether","3":"TwistingNether","4":"PvE","5":"enGB","7":"EU","8":"UTC+1","9":"table: 0000025DE1051D30","12":"|TInterface\AddOns\TooltipRealmInfo\media\enGB:0:2|t","13":"Interface\AddOns\TooltipRealmInfo\media\enGB"}|r
|cff99999919:18:29|r |cff82c5ffTooltipRealmInfo|r: |cff00ff00<CCF>|r |cffff6060nil|r |cff44ffff14|r |cffffff00Player-3674-08D03F53|r |cffff8800table|r |cffff44ff{"1":"625","2":"Twisting Nether","3":"TwistingNether","4":"PvE","5":"enGB","7":"EU","8":"UTC+1","9":"table: 0000025DE1051FB0","12":"|TInterface\AddOns\TooltipRealmInfo\media\enGB:0:2|t","13":"Interface\AddOns\TooltipRealmInfo\media\enGB"}|r

Das stand in der Konsole, als jemand von Twisting Nether geschrieben hat. Dort hätte eigentlich die GB Flagge erscheinen müssen. Ist aber wie schon eingangs beschrieben nicht passiert :)

**Comment by hizuro** [comment]
Die Ausgabe sollte es auch nur geben, wenn der Chatfilter keine Flagge hinzugefügt hat.
Oh. Der DK hat ja einen sehr einfallsreichen Namen. ;-)

So hab mal eine Alpha Version hochgeladen. Die Debug Ausgabe ist geändert. Und die TooltipRealmInfo.lua aus SavedVariables bräuchte ich noch.

Das If vor dem Hinzufügen dürfte nur bei der 3. Expression false ergeben. Auch wenn ich es seltsam finde. 

**Nachtrag: Peinlich. Einen Fehler eingebaut. Noch ein Update... ;-)**

**Comment by sprenger-hauke** [comment]
> TooltipRealmInfoDB = {
	["ttGrpFinder"] = true,
	["frFR_countryflag"] = true,
	["RAID_countryflag"] = true,
	["timezone"] = false,
	["ttPlayer"] = true,
	["deDE_countryflag"] = true,
	["INSTANCE_countryflag"] = true,
	["loadedmessage"] = true,
	["language"] = true,
	["BG_countryflag"] = true,
	["CHANNEL_countryflag"] = true,
	["type"] = false,
	["SAY_countryflag"] = true,
	["communities_countryflag"] = true,
	["countryflag"] = "languageline",
	["connectedrealms"] = false,
	["finder_counryflag"] = true,
	["ttFriends"] = true,
	["ptBR_countryflag"] = true,
	["PARTY_countryflag"] = true,
	["enUS_countryflag"] = true,
	["esES_countryflag"] = true,
	["ruRU_countryflag"] = true,
	["WHISPER_countryflag"] = true,
	["itIT_countryflag"] = true,
}

Wenn ich da so drüber schaue, kann ich kein Setting sehen für enGB. Liegt es evtl. daran? Evtl. muss enUS und enGB gesondert betrachtet werden.

Edit: Hab die neue Version nu noch nicht getestet. War gerade am grillen :D.

**Comment by sprenger-hauke** [comment]
Hab nu mal die neue alpha genommen (TooltipRealmInfo-1.2.9-alpha2.zip)

Nun steht in der lua nur

> TooltipRealmInfoDB = nil

Und man kann auch per /ttri config nicht mehr die config öffnen.  Keine Ahnung ob das so gewollt war/ist.

**Comment by hizuro** [comment]
Ja. Der WoW Client führt intern leider enGB als enUS. Bei ptPT/ptBR auch, ist mir aber erst heute aufgefallen. 

> TooltipRealmInfoDB = nil

Oje. Das war gar nicht gewollt..

\*\* Panic \*\*

**Comment by sprenger-hauke** [comment]
Ja, er zeigt nu auch nur noch Flaggen im Tooltip an und nicht mehr im Chat :D

€: So ist es halt oftmals beim coden... Man fixt einen Bug und erstellt einen neuen...

**Comment by hizuro** [comment]
Jo. Hab ihn schon gefunden xD Upload is raus. 
Toll. Noch ein Bug.
*So. Alpha4*

**Comment by sprenger-hauke** [comment]
> Jo. Hab ihn schon gefunden xD Upload is raus. Toll. Noch ein Bug. _So. Alpha4_

Gerade geladen, ich schaue nochmal :)

**Comment by sprenger-hauke** [comment]
Funktioniert jetzt ;)

**Comment by hizuro** [comment]
Super. Und Danke für deine Hilfe und Geduld. ;-)
